# Default values for circleci-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# You can extend a custom image from our runner and use
# that repository instead. See:
# https://circleci.com/docs/2.0/runner-installation/?section=executors-and-images#create-a-dockerfile-that-extends-the-circleci-runner-image
image:
  repository: docker.mediamath.com/circleci/runner
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "poc"

configSecret:
  create: true
  name: config-values

serviceAccount:
  create: false
  name: cicd
  annotations: {}
#    eks.amazonaws.com/role-arn: "arn:aws:iam:..."

# Refers to the resource class you created for your runner. See:
# https://circleci.com/docs/2.0/runner-installation/?section=executors-and-images#authentication
resourceClass: ""
# Runner API token. See:
# https://circleci.com/docs/2.0/runner-installation/
runnerToken: ""

# The agent version to use for CircleCI Enterprise installations
agentVersion: ""

imagePullSecrets:
  - name: mm-artifactory

dockerPull: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {
        runAsUser: 1500
}

resources:
  limits:
    cpu: "200m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "1Gi"

resourcesDinD:
  limits:
    cpu: "200m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "1Gi"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: "LAUNCH_AGENT_RUNNER_SSH_ADVERTISE_ADDR"
    value: "10.128.88.216:54782"
