version: 2

helm_defaults: &helm_defaults
  docker:
    - image: docker.mediamath.com/techops/cci/cci-utility-helm:3.6.1
      auth:
        username: $ARTIFACTORY_USER
        password: $ARTIFACTORY_PASSWORD
  steps:
    - checkout
    - run:
        name: Set KubeConfig
        command: |
          mkdir ~/.kube/
          if [ $KUBECREDS == "prd" ]; then
            echo $KUBECONFIG_PRD | openssl base64 -d -A > ~/.kube/config
            echo "export RUNNER_TOKEN=$CCI_RUNNER_TOKEN_PRD" >> $BASH_ENV
            echo "export RUNNER_RESOURCE_CLASS=$CCI_RUNNER_RESOURCE_CLASS_PRD" >> $BASH_ENV
          else
            echo $KUBECONFIG_NP | openssl base64 -d -A > ~/.kube/config
            echo "export RUNNER_TOKEN=$CCI_RUNNER_TOKEN_NP" >> $BASH_ENV
            echo "export RUNNER_RESOURCE_CLASS=$CCI_RUNNER_RESOURCE_CLASS_NP" >> $BASH_ENV
          fi
          chmod 600 ~/.kube/config
    - run:
        name: Helm Install/Upgrade
        command: |
          helm upgrade --install -f values.yaml circleci-runners ./ --set runnerToken=$RUNNER_TOKEN --set resourceClass=$RUNNER_RESOURCE_CLASS --set env.runner.ssh.advertise_addr=10.10.10.10:54782 --namespace circleci-runners $DRYRUN

jobs:
  dev-test:
    environment:
      KUBECREDS: "np"
      DRYRUN: "--dry-run"
    <<: *helm_defaults
  dev-deploy:
    environment:
      KUBECREDS: "np"
      DRYRUN: ""
    <<: *helm_defaults
  prod-test:
    environment:
      KUBECREDS: "prd"
      DRYRUN: "--dry-run"
    <<: *helm_defaults
  prod-deploy:
    environment:
      KUBECREDS: "prd"
      DRYRUN: ""
    <<: *helm_defaults

workflows:
  version: 2
  cci-runners:
    jobs:
      - dev-test:
          context: mediamath
      - dev-approval:
          type: approval
          requires:
            - dev-test
      - dev-deploy:
          context: mediamath
          requires:
            - dev-approval
      - prod-test:
          context: mediamath
          requires:
            - dev-deploy
          filters:
            branches:
              only:
                - main
      - prod-approval:
          type: approval
          requires:
            - prod-test
          filters:
            branches:
              only:
                - main
      - prod-deploy:
          context: mediamath
          requires:
            - prod-approval
          filters:
            branches:
              only:
                - main