version: 2
jobs:
  helm:
    docker:
      - image: docker.mediamath.com/techops/cci/cci-utility-helm:3.6.1
        auth:
          username: $ARTIFACTORY_USER
          password: $ARTIFACTORY_PASSWORD
    steps:
      - checkout
      - run: mkdir ~/.kube/ && echo $KUBECONFIG_NP | openssl base64 -d -A > ~/.kube/config
      - run:
          name: Install or Upgrade Staging K8S
          command: |
            #need to update the local index of the remote chart repo
            kubectl config get-contexts
            kubectl config set-context circleci-runners
            kubectl config get-contexts -n circleci-runners

workflows:
  version: 2
  cci-runners:
    jobs:
      - helm:
          context: mediamath
