version: 2

helm_defaults: &helm_defaults
  docker:
    - image: docker.mediamath.com/techops/cci/cci-utility-helm:3.6.1
      auth:
        username: $ARTIFACTORY_USER
        password: $ARTIFACTORY_PASSWORD
  steps:
    - checkout
    - run:
        name: Set KubeConfig
        command: |
          mkdir ~/.kube/ && \
          echo $KUBECONFIG | openssl base64 -d -A > ~/.kube/config && \
          chmod 600 ~/.kube/config
    - run:
        name: Helm Install/Upgrade
        command: |
          helm upgrade --install -f values.yaml circleci-runners ./ --set runnerToken=$RUNNER_TOKEN --set resourceClass=$RUNNER_RESOURCECLASS --namespace circleci-runners $DRYRUN

jobs:
  helm-test:
    environment:
      KUBECONFIG: ${KUBECONFIG_NP}
      DRYRUN: "--dry-run"
      RUNNER_TOKEN: ${CCI_RUNNER_TOKEN}
      RUNNER_RESOURCECLASS: ${CCI_RUNNER_RESOURCECLASS}
    <<: *helm_defaults
  dev-deploy:
    environment:
      KUBECONFIG: ${KUBECONFIG_NP}
      DRYRUN: ""
      RUNNER_TOKEN: ${CCI_RUNNER_TOKEN}
      RUNNER_RESOURCECLASS: ${CCI_RUNNER_RESOURCECLASS}
    <<: *helm_defaults
  prod-deploy:
    environment:
      PRUEBA: "prueba3"
    <<: *helm_defaults

workflows:
  version: 2
  cci-runners:
    jobs:
      - helm-test:
          context: mediamath
      - dev-approval:
          type: approval
          requires:
            - helm-test
          filters:
            branches:
              ignore:
                - main
      - dev-deploy:
          context: mediamath
          requires:
            - dev-approval
          filters:
            branches:
              ignore:
                - main
      - prod-approval:
          type: approval
          requires:
            - helm-test
          filters:
            branches:
              only:
                - main
      - prod-deploy:
          context: mediamath
          requires:
            - prod-approval
          filters:
            branches:
              only:
                - main