version: 2

helm_defaults: &helm_defaults
  docker:
    - image: docker.mediamath.com/techops/cci/cci-utility-helm:3.6.1
      auth:
        username: $ARTIFACTORY_USER
        password: $ARTIFACTORY_PASSWORD
  steps:
    - checkout
    - run:
        name: Set KubeConfig
        command: |
          mkdir ~/.kube/
          if [ $KUBECONFIG == "prd" ]; then
            echo $KUBECONFIG_PRD | openssl base64 -d -A > ~/.kube/config
          else
            echo $KUBECONFIG_NP | openssl base64 -d -A > ~/.kube/config
          fi
          chmod 600 ~/.kube/config
    - run:
        name: Helm Install/Upgrade
        command: |
          helm upgrade --install -f values.yaml circleci-runners ./ --set runnerToken=$CCI_RUNNER_TOKEN --set resourceClass=$CCI_RUNNER_RESOURCECLASS --namespace circleci-runners $DRYRUN

jobs:
  helm-test:
    environment:
      KUBECONFIG: "np"
      DRYRUN: "--dry-run"
    <<: *helm_defaults
  dev-deploy:
    environment:
      KUBECONFIG: "np"
      DRYRUN: ""
    <<: *helm_defaults
  prod-deploy:
    environment:
      KUBECONFIG: "prd"
      DRYRUN: ""
    <<: *helm_defaults

workflows:
  version: 2
  cci-runners:
    jobs:
      - helm-test:
          context: mediamath
      - dev-approval:
          type: approval
          requires:
            - helm-test
      - dev-deploy:
          context: mediamath
          requires:
            - dev-approval
      - prod-approval:
          type: approval
          requires:
            - helm-test
          filters:
            branches:
              only:
                - main
      - prod-deploy:
          context: mediamath
          requires:
            - prod-approval
          filters:
            branches:
              only:
                - main