version: 2
jobs:
  helm:
    docker:
      - image: docker.mediamath.com/techops/cci/cci-utility-helm:3.6.1
        auth:
          username: $ARTIFACTORY_USER
          password: $ARTIFACTORY_PASSWORD
    steps:
      - checkout
      - run:
          name: Set KubeConfig
          command: |
             mkdir ~/.kube/ && echo $KUBECONFIG_NP | openssl base64 -d -A > ~/.kube/config && chmod 600 ~/.kube/config
      - run:
          name: Helm Upgrade
          command: |
             helm upgrade --install -f values.yaml circleci-runners ./ --set runnerToken='TEST' --set resourceClass='mediamath/circleci-poc' --namespace circleci-runners --dry-run

workflows:
  version: 2
  cci-runners:
    jobs:
      - helm:
          context: mediamath
